
# docker-compose.yml
version: '3'
services:
  NLP_python:
    container_name: NLP_python
    image: docker-nlp-python:latest
    volumes: # persist data even if container shuts down
      - ${GIT_REPO_PATH}/notebooks:/home/ml_user/notebooks
      - ${SHARE_DATA_PATH}/work:/home/ml_user/work
      - ${SHARE_DATA_PATH}/data:/home/ml_user/data
    ports:
      - "8888:8888"
      - "3000:3000"
    restart: 'no'
    command: jupyter lab --notebook-dir=/home/ml_user/notebooks --ip=0.0.0.0 --port=8888 --no-browser
  NLP_mongo:
    container_name: NLP_mongo
    image: mongo:4.4.9-focal # Use the official MongoDB image
    volumes: # persist data even if container shuts down
      - ${SHARE_DATA_PATH}/mongo/data/db:/data/mongo/db
    ports:
      - "27017:27017"
  # webserver:
  #   container_name: airflow_testing_local
  #   image: puckel/docker-airflow:1.10.9 # use an unofficial image when no official one exist
  #   ports:
  #     - "8085:8080"
  #   volumes:
  #     - ${SHARE_DATA_PATH}/share:/usr/local/airflow/share
  #     # - ${SHARE_DATA_PATH}/airflow/airflow.db:/usr/local/airflow/airflow.db
  #     - ${GIT_REPO_PATH}/airflow/plugins:/usr/local/airflow/plugins
  #     - ${GIT_REPO_PATH}/testing/airflow-config/requirements.txt:/requirements.txt # Should decide whether to mount files from repository or copy.
  #     - ${GIT_REPO_PATH}/testing/airflow-config/airflow.cfg:/usr/local/airflow/airflow.cfg # Should decide whether to mount files from repository or copy.
  #     - ${GIT_REPO_PATH}/airflow/dags:/usr/local/airflow/dags # Should decide whether to mount files from repository or copy.
